### ISSUE TITLE
Error parsing non-float episodes

### ISSUE THREAD

**Issue by baxa73** [Jelomite/horrible-downloader#23]
FETCHING: Re Zero kara Hajimeru Isekai Seikatsu - Director's Cut
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/HorribleDownloader/cmd.py", line 121, in fetch_episodes
    new = list(filter(lambda s: ep_filter(s["episode"]), episodes))
  File "/usr/local/lib/python3.6/dist-packages/HorribleDownloader/cmd.py", line 121, in <lambda>
    new = list(filter(lambda s: ep_filter(s["episode"]), episodes))
  File "/usr/local/lib/python3.6/dist-packages/HorribleDownloader/cmd.py", line 86, in generated_filter
    return any([test(float(ep)) for test in tests])
  File "/usr/local/lib/python3.6/dist-packages/HorribleDownloader/cmd.py", line 86, in <listcomp>
    return any([test(float(ep)) for test in tests])
ValueError: could not convert string to float: '01B'
Couldn't find specified anime. Exiting

**Comment by mtshrmn** [comment]
Thank you for using horrible-downloader!
Can you please tell me what did you do, what is the expected result and what os are you using?

**Comment by baxa73** [comment]
Downloaded title "Re Zero kara Hajimeru Isekai Seikatsu - Director's Cut", then I got this error.
All is well with the other titles.

Downloaded with this command: (horrible-downloader -d "Re Zero kara Hajimeru Isekai Seikatsu - Director's Cut" -e 1)

OC: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-169-generic x86_64)

**Comment by baxa73** [comment]
I think the problem is that on the same page, the place immediately two different versions and so the loader cannot understand which one to pump out.

**Comment by mtshrmn** [comment]
I will try to work on a solution this week. Sorry for keeping you waiting.

**Comment by mtshrmn** [comment]
The new re:zero season brought back this issue. It's a bit annoying having letters in the title and parsing it is weird.
horriblesubs.info don't sort stuff logically and it's adding to the complexity. It would be nice to solve this issue but because this is happening only with this specific anime, I prefer to just ignore it.

If anyone wants to try and tackle the problem, go ahead, I'll be glad.
